=== Davisa94/public_html/week08/head.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT head (title, base?, style?, meta*)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT style (#PCDATA)>
<!ELEMENT base EMPTY>
<!ELEMENT meta EMPTY>
<!ATTLIST base href CDATA #REQUIRED>
<!ATTLIST base target CDATA #REQUIRED>
<!ATTLIST meta name CDATA #REQUIRED>
<!ATTLIST meta content CDATA #REQUIRED>

=== Davisa94/public_html/week08/head.xml
<?xml version="1.0" encoding = "UTF-8"?>
<!DOCTYPE head SYSTEM "head.dtd">
<head>
   <title>Teach One Another - Week 08</title>
   <base href="http://www.byui.edu/" target="_blank"></base>
   <style>h1 {color:red}</style>
   <meta name="author" content="Br. Helfrich"></meta>
   <meta name="class" content="CS 213"></meta>
   <meta name="activity" content="Teach One Another"></meta>
   <meta name="problem" content="2"></meta>
</head>
